version: "3.4"
services:
  geth.dnp.dappnode.eth:
    image: "geth.dnp.dappnode.eth:0.1.17"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.10.20
    volumes:
      - "geth:/root/.ethereum"
    environment:
      - "EXTRA_OPTIONS=--http.api eth,net,web3,txpool"
      - P2P_PORT=30304
      - SYNCMODE=snap
    ports:
      - "30304:30304/tcp"
      - "30304:30304/udp"
    restart: unless-stopped
volumes:
  geth: {}
